
import React from 'react';
import { AlertCircleIcon } from 'lucide-react';

const Disclaimer: React.FC = () => {
  return (
    <section id="disclaimer" className="py-20 relative overflow-hidden">
      {/* Enhanced animated background */}
      <div className="absolute inset-0">
        <div className="absolute top-0 left-0 w-full h-full bg-cyberpunk-grid bg-[size:50px_50px] opacity-10 animate-pulse"></div>
        <div className="absolute top-1/4 left-1/4 w-3 h-3 bg-cyberpunk-primary rounded-full animate-ping opacity-40"></div>
        <div className="absolute top-3/4 right-1/4 w-2 h-2 bg-cyberpunk-secondary rounded-full animate-bounce opacity-50"></div>
        <div className="absolute top-1/2 left-1/3 w-1 h-1 bg-cyberpunk-accent rounded-full animate-pulse opacity-60"></div>
        <div className="absolute bottom-1/4 right-1/3 w-2 h-2 bg-cyberpunk-primary rounded-full animate-ping opacity-30 animation-delay-1000"></div>
      </div>

      <div className="container mx-auto px-4 relative z-10">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            <span className="neon-text-primary">Legal</span> Disclaimer
          </h2>
          <p className="max-w-2xl mx-auto text-cyberpunk-foreground/80 flex items-center justify-center">
            <AlertCircleIcon className="mr-2 text-cyberpunk-primary" size={20} />
            Important information about using AD MAKER GPT
          </p>
        </div>

        <div className="max-w-4xl mx-auto bg-cyberpunk-muted/30 backdrop-blur-sm rounded-lg p-8 cyberpunk-border shadow-2xl">
          <div className="space-y-6 text-cyberpunk-foreground/80">
            <p>
              <strong>General Disclaimer:</strong> AD MAKER GPT is provided "as is" without warranties of any kind, either express or implied. AI WEB TOOLS LLC does not warrant that the service will be uninterrupted or error-free. Your use of AD MAKER GPT is at your own risk.
            </p>
            
            <p>
              <strong>Content Generation:</strong> While AD MAKER GPT strives to generate high-quality, appropriate content, AI WEB TOOLS LLC is not responsible for any content generated by the tool. Users are responsible for reviewing, approving, and ensuring the legality and appropriateness of all generated advertisements before use.
            </p>
            
            <p>
              <strong>Intellectual Property:</strong> By using AD MAKER GPT, you represent and warrant that you have the legal right to use any logos, trademarks, or other content you upload or request to be incorporated into advertisements. AI WEB TOOLS LLC assumes no responsibility for any copyright or trademark infringement resulting from user-provided content.
            </p>
            
            <p>
              <strong>Limitation of Liability:</strong> AI WEB TOOLS LLC shall not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages resulting from your use of AD MAKER GPT, including but not limited to damages for loss of profits, goodwill, data, or other intangible losses.
            </p>
            
            <p>
              <strong>Third-Party Links:</strong> AD MAKER GPT may contain links to third-party websites or services that are not owned or controlled by AI WEB TOOLS LLC. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party websites or services.
            </p>
            
            <p>
              <strong>Compliance with Laws:</strong> Users are responsible for ensuring that their use of AD MAKER GPT and any advertisements created through it comply with all applicable local, state, national, and international laws and regulations.
            </p>
            
            <p>
              <strong>Changes to Service:</strong> AI WEB TOOLS LLC reserves the right to modify or discontinue, temporarily or permanently, the AD MAKER GPT service with or without notice at any time.
            </p>
            
            <p>
              <strong>User Agreement:</strong> By accessing and using AD MAKER GPT, you agree to be bound by the terms of this disclaimer as well as our <a href="https://aiwebtools.lovable.app/disclaimers" className="text-cyberpunk-secondary hover:underline" target="_blank" rel="noopener noreferrer">Terms of Service</a> and <a href="https://openai.com/policies/privacy-policy/" className="text-cyberpunk-secondary hover:underline" target="_blank" rel="noopener noreferrer">Privacy Policy</a>.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Disclaimer;
