
import React from 'react';
import { MessageCircleIcon, ImageIcon, FileTextIcon, RefreshCwIcon, DownloadIcon } from 'lucide-react';

const HowItWorks: React.FC = () => {
  const steps = [
    {
      icon: <MessageCircleIcon size={28} />,
      title: "Answer Simple Questions",
      description: "Tell AD MAKER GPT about your brand, goals, target audience, and preferences.",
      color: "primary"
    },
    {
      icon: <ImageIcon size={28} />,
      title: "Get Ad Outline",
      description: "AD MAKER GPT creates a detailed outline for your advertisement based on your input.",
      color: "secondary"
    },
    {
      icon: <FileTextIcon size={28} />,
      title: "Generate 5 Variations",
      description: "Instantly receive 5 unique advertisement designs generated by GPT-4o.",
      color: "accent"
    },
    {
      icon: <RefreshCwIcon size={28} />,
      title: "Request Adjustments",
      description: "Request changes to any aspect of the ads until they perfectly match your vision.",
      color: "primary"
    },
    {
      icon: <DownloadIcon size={28} />,
      title: "Download Your Ads",
      description: "Save your finalized advertisements for immediate use in your marketing campaigns.",
      color: "secondary"
    }
  ];

  return (
    <section id="how-it-works" className="py-20 relative overflow-hidden">
      <div className="container mx-auto px-4 relative z-10">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            How <span className="neon-text-primary">AD MAKER GPT</span> Works
          </h2>
          <p className="max-w-2xl mx-auto text-cyberpunk-foreground/80">
            Creating professional advertisements has never been easier. Follow these simple steps to generate stunning, personalized ads in minutes.
          </p>
        </div>

        <div className="relative">
          {/* Step line */}
          <div className="hidden md:block absolute left-1/2 top-8 bottom-8 w-0.5 bg-gradient-to-b from-cyberpunk-primary via-cyberpunk-secondary to-cyberpunk-accent"></div>
          
          {/* Steps */}
          <div className="space-y-16">
            {steps.map((step, index) => (
              <div key={index} className="flex flex-col md:flex-row items-center">
                <div className={`md:w-1/2 ${index % 2 === 0 ? 'md:text-right md:pr-16' : 'md:order-2 md:text-left md:pl-16'}`}>
                  <h3 className={`text-2xl font-bold mb-3 neon-text-${step.color}`}>
                    {index + 1}. {step.title}
                  </h3>
                  <p className="text-cyberpunk-foreground/70 max-w-lg mx-auto md:mx-0">
                    {step.description}
                  </p>
                </div>
                
                {/* Icon */}
                <div className={`relative my-6 md:my-0 z-10 ${index % 2 === 0 ? '' : 'md:order-1'}`}>
                  <div className={`w-16 h-16 rounded-full bg-cyberpunk-muted border border-cyberpunk-${step.color} shadow-neon-${step.color} flex items-center justify-center`}>
                    {step.icon}
                  </div>
                  {/* Step number badges for mobile */}
                  <div className="absolute -top-2 -right-2 w-6 h-6 rounded-full bg-cyberpunk-muted border border-cyberpunk-secondary flex items-center justify-center text-xs font-bold md:hidden">
                    {index + 1}
                  </div>
                </div>
                
                {/* Empty div for grid layout */}
                <div className={`md:w-1/2 ${index % 2 === 0 ? 'md:order-2' : ''}`}></div>
              </div>
            ))}
          </div>
        </div>
        
        <div className="mt-20 text-center">
          <a 
            href="https://chatgpt.com/g/g-6810ea3238888191a084c4f20b40225f-ad-maker-gpt"
            className="cyberpunk-button"
            target="_blank"
            rel="noopener noreferrer"
          >
            <span>GET STARTED NOW</span>
          </a>
        </div>
      </div>
      
      {/* Background decorative elements */}
      <div className="absolute inset-0 bg-cyberpunk-grid bg-[size:50px_50px] opacity-10"></div>
      <div className="absolute top-20 right-10 w-72 h-72 bg-cyberpunk-accent/10 rounded-full filter blur-[80px]"></div>
    </section>
  );
};

export default HowItWorks;
